import { StyleSheet } from 'react-native';

const shadow = {
  elevation: 8,
  shadowColor: '#061425',
  shadowOffset: { width: 0, height: 10 },
  shadowOpacity: 0.12,
  shadowRadius: 20,
};

export const styles = StyleSheet.create({
  authContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
  },
  authCopy: {
    color: '#c2d4e9',
    fontSize: 15,
    lineHeight: 23,
    marginTop: 12,
  },
  authEyebrow: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 32,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    opacity: 0.8,
  },
  authHero: {
    backgroundColor: '#086cf2',
    minHeight: 480,
    overflow: 'hidden',
    padding: 30,
  },
  authBlobLarge: {
    backgroundColor: 'rgba(255,255,255,0.11)',
    borderRadius: 120,
    height: 230,
    position: 'absolute',
    right: -58,
    top: -52,
    width: 230,
  },
  authBlobSmall: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 70,
    bottom: 108,
    height: 124,
    left: -32,
    position: 'absolute',
    width: 124,
  },
  authLanguageButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderColor: 'rgba(255,255,255,0.25)',
    borderRadius: 14,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    position: 'absolute',
    right: 18,
    top: 18,
    width: 54,
  },
  authLanguageText: {
    color: '#ffffff',
    fontWeight: '900',
  },
  authWave: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 1000,
    borderTopRightRadius: 1000,
    bottom: -300,
    height: 400,
    left: -250,
    position: 'absolute',
    right: -250,
  },
  authPanel: {
    ...shadow,
    backgroundColor: '#ffffff',
    borderColor: 'rgba(255, 255, 255, 0.8)',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderWidth: 1,
    gap: 18,
    marginTop: -60,
    padding: 30,
  },
  authPreview: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 30,
    padding: 16,
  },
  authScreen: {
    backgroundColor: '#086cf2',
    flex: 1,
  },
  authTitle: {
    color: '#ffffff',
    fontSize: 37,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 46,
    marginTop: 8,
  },
  brandHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 12,
  },
  brandLogo: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: 'rgba(255,255,255,0.28)',
    borderRadius: 16,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    width: 52,
    overflow: 'hidden',
  },
  brandLogoImage: {
    width: '100%',
    height: '100%',
  },
  brandName: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  commentInput: {
    backgroundColor: '#f5f8fc',
    borderColor: '#e2e9f3',
    borderRadius: 14,
    borderWidth: 1,
    color: '#101b2d',
    fontSize: 14,
    minHeight: 94,
    padding: 14,
    textAlignVertical: 'top',
  },
  commentText: {
    color: '#506176',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
  },
  content: {
    gap: 14,
    padding: 16,
    paddingBottom: 110,
  },
  detail: {
    color: '#627188',
    fontSize: 14,
    lineHeight: 22,
  },
  emptyText: {
    color: '#d7e8f8',
    fontWeight: '900',
    textAlign: 'center',
  },
  eyebrow: {
    color: '#67d8ff',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: '#f4f7fb',
    borderColor: '#e3eaf4',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 42,
  },
  filterChipActive: {
    backgroundColor: '#101b2d',
    borderColor: '#101b2d',
  },
  filterChipText: {
    color: '#65758b',
    fontWeight: '900',
    textTransform: 'capitalize',
  },
  filterChipTextActive: {
    color: '#ffffff',
  },
  filterChips: {
    flexDirection: 'row',
    gap: 8,
  },
  filterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterGridInput: {
    flex: 1,
    minWidth: '30%',
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#071525',
    borderBottomColor: 'rgba(255,255,255,0.08)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 18,
    paddingBottom: 16,
  },
  headerCopy: {
    flex: 1,
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  input: {
    backgroundColor: '#f6f9fd',
    borderColor: '#e0e8f2',
    borderRadius: 15,
    borderWidth: 1.5,
    color: '#101b2d',
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: 18,
    marginBottom: 2,
  },
  legendDense: {
    backgroundColor: '#ff2323',
  },
  legendLight: {
    backgroundColor: '#12e627',
  },
  legendMedium: {
    backgroundColor: '#ffe01e',
  },
  legendRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  legendSwatch: {
    borderColor: 'rgba(255,255,255,0.5)',
    borderRadius: 4,
    borderWidth: 1,
    height: 12,
    width: 12,
  },
  legendText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },
  languageButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 48,
  },
  languageText: {
    color: '#67d8ff',
    fontSize: 12,
    fontWeight: '900',
  },
  loadingScreen: {
    alignItems: 'center',
    backgroundColor: '#071525',
    flex: 1,
    justifyContent: 'center',
  },
  loadingText: {
    color: '#c2d4e9',
    fontSize: 15,
    marginTop: 12,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 14,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  mapEmpty: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    backgroundColor: 'rgba(7,21,37,0.72)',
    justifyContent: 'center',
    padding: 24,
  },
  mapFrame: {
    aspectRatio: 0.82,
    backgroundColor: '#0b1728',
    borderColor: '#10243b',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  mapFrameFull: {
    aspectRatio: undefined,
    borderRadius: 0,
    borderWidth: 0,
    flex: 1,
    marginHorizontal: -16,
    marginTop: -16,
    marginBottom: -110,
    minHeight: 800,
  },
  mapLegend: {
    backgroundColor: 'rgba(7,21,37,0.88)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    borderWidth: 1,
    top: 225,
    gap: 7,
    left: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'absolute',
  },
  mapToolbar: {
    backgroundColor: 'rgba(7,21,37,0.9)',
    borderBottomColor: 'rgba(255,255,255,0.1)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  mapToolbarMeta: {
    color: '#67d8ff',
    fontSize: 12,
    fontWeight: '900',
  },
  mapToolbarTitle: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  adminMapScreen: {
    flex: 1,
    minHeight: 800,
  },
  mapFilterMeta: {
    color: '#6d7f94',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  mapFilterStrip: {
    ...shadow,
    backgroundColor: '#ffffff',
    borderColor: '#edf2f8',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  mapFilterTitle: {
    color: '#101b2d',
    fontSize: 18,
    fontWeight: '900',
  },
  mapQuickFilters: {
    flexDirection: 'row',
    gap: 8,
    left: 12,
    position: 'absolute',
    right: 12,
    top: 60,
    zIndex: 10,
  },
  mapSearchInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderColor: 'rgba(255, 255, 255, 0.35)',
    borderRadius: 15,
    borderWidth: 1,
    color: '#101b2d',
    flex: 1,
    minHeight: 48,
    paddingHorizontal: 13,
  },
  mapSearchInputActive: {
    backgroundColor: '#ffffff',
    borderColor: '#ffffff',
  },
  mapInspector: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderColor: 'rgba(16,27,45,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    bottom: 12,
    gap: 9,
    padding: 13,
    position: 'absolute',
    right: 12,
    width: 260,
  },
  inspectorClose: {
    alignItems: 'center',
    backgroundColor: '#eef3f8',
    borderRadius: 11,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  inspectorCloseText: {
    color: '#101b2d',
    fontWeight: '900',
  },
  inspectorEmail: {
    color: '#6d7f94',
    fontSize: 12,
    marginTop: 2,
  },
  inspectorLocation: {
    color: '#516174',
    fontSize: 12,
    fontWeight: '800',
  },
  inspectorName: {
    color: '#101b2d',
    fontSize: 15,
    fontWeight: '900',
  },
  inspectorStat: {
    backgroundColor: '#eef8ff',
    borderRadius: 12,
    color: '#087cc2',
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 8,
    textAlign: 'center',
  },
  inspectorStats: {
    flexDirection: 'row',
    gap: 8,
  },
  inspectorTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metricAccent: {
    backgroundColor: '#0ea5ff',
    borderRadius: 6,
    height: 38,
    width: 5,
  },
  metricAccentStrong: {
    backgroundColor: '#ffffff',
  },
  metricCard: {
    ...shadow,
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#eef3f9',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 96,
    minWidth: '47%',
    padding: 14,
  },
  metricCardStrong: {
    backgroundColor: '#0ea5ff',
    borderColor: '#0ea5ff',
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metricLabel: {
    color: '#7a8799',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  metricValue: {
    color: '#101b2d',
    fontSize: 22,
    fontWeight: '900',
    marginTop: 7,
  },
  metricTextStrong: {
    color: '#ffffff',
  },
  modeButton: {
    alignItems: 'center',
    borderRadius: 13,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
  },
  modeButtonActive: {
    backgroundColor: '#101b2d',
  },
  modeSwitch: {
    backgroundColor: '#eef3f8',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 5,
    padding: 5,
  },
  modeText: {
    color: '#65758b',
    fontWeight: '900',
  },
  modeTextActive: {
    color: '#ffffff',
  },
  panel: {
    ...shadow,
    backgroundColor: '#ffffff',
    borderColor: '#edf2f8',
    borderRadius: 20,
    borderWidth: 1,
    gap: 13,
    padding: 16,
  },
  previewBadge: {
    backgroundColor: 'rgba(28, 205, 104, 0.18)',
    borderColor: 'rgba(28, 205, 104, 0.34)',
    borderRadius: 12,
    borderWidth: 1,
    color: '#8cffb9',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  previewGauge: {
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: '#0ea5ff',
    borderRadius: 74,
    borderRightColor: 'rgba(14,165,255,0.18)',
    borderWidth: 14,
    height: 148,
    justifyContent: 'center',
    marginVertical: 14,
    width: 148,
  },
  previewGaugeInner: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 54,
    height: 108,
    justifyContent: 'center',
    width: 108,
  },
  previewGaugeLabel: {
    color: '#9bb4ce',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  previewGaugeValue: {
    color: '#ffffff',
    fontSize: 35,
    fontWeight: '900',
  },
  previewHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  previewStat: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    padding: 10,
  },
  previewStatLabel: {
    color: '#9bb4ce',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 3,
  },
  previewStatValue: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
  },
  previewStats: {
    flexDirection: 'row',
    gap: 9,
  },
  previewTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#0ea5ff',
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 16,
  },
  speedArc: {
    borderColor: '#0ea5ff',
    borderLeftColor: '#dceefa',
    borderRadius: 92,
    borderRightColor: '#dceefa',
    borderWidth: 16,
    height: 184,
    position: 'absolute',
    top: 8,
    width: 184,
  },
  speedGauge: {
    alignItems: 'center',
    height: 200,
    justifyContent: 'center',
  },
  speedHub: {
    backgroundColor: '#0ea5ff',
    borderColor: '#ffffff',
    borderRadius: 11,
    borderWidth: 4,
    height: 22,
    left: '50%',
    marginLeft: -11,
    position: 'absolute',
    top: 100,
    width: 22,
  },
  speedLabel: {
    color: '#78889a',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 6,
  },
  speedNeedle: {
    backgroundColor: '#101b2d',
    borderRadius: 5,
    height: 8,
    position: 'absolute',
    left: '50%',
    marginLeft: -76,
    top: 107,
    transformOrigin: 'right center',
    width: 76,
  },
  speedPanel: {
    ...shadow,
    backgroundColor: '#ffffff',
    borderColor: '#edf2f8',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 16,
  },
  speedStat: {
    backgroundColor: '#f5f8fc',
    borderColor: '#e6eef7',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    padding: 13,
  },
  speedStatLabel: {
    color: '#7a8799',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 4,
  },
  speedStatValue: {
    color: '#101b2d',
    fontSize: 18,
    fontWeight: '900',
  },
  speedStats: {
    flexDirection: 'row',
    gap: 10,
  },
  speedResult: {
    alignItems: 'center',
    marginBottom: 20,
  },
  speedValue: {
    color: '#101b2d',
    fontSize: 36,
    fontWeight: '900',
  },
  speedUnit: {
    color: '#78889a',
    fontSize: 14,
    fontWeight: '700',
    marginTop: -4,
  },
  speedTick: {
    position: 'absolute',
    top: 105,
    left: '50%',
    width: 20,
    marginLeft: -10,
    alignItems: 'center',
  },
  speedTickText: {
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: '800',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  ratingButton: {
    alignItems: 'center',
    backgroundColor: '#f4f7fb',
    borderColor: '#e2e9f3',
    borderRadius: 13,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  ratingButtonActive: {
    backgroundColor: '#101b2d',
    borderColor: '#101b2d',
  },
  ratingButtons: {
    flexDirection: 'row',
    gap: 7,
  },
  ratingLabel: {
    color: '#263244',
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  ratingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  ratingText: {
    color: '#3c4858',
    fontWeight: '900',
  },
  ratingTextActive: {
    color: '#ffffff',
  },
  recordBadge: {
    backgroundColor: '#eaf6ff',
    borderRadius: 12,
    color: '#0d84d4',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
    textTransform: 'uppercase',
  },
  recordCard: {
    ...shadow,
    backgroundColor: '#ffffff',
    borderColor: '#edf2f8',
    borderRadius: 18,
    borderWidth: 1,
    padding: 15,
  },
  recordDate: {
    color: '#7b8796',
    fontSize: 12,
    marginTop: 3,
  },
  recordDetails: {
    borderTopColor: '#edf2f8',
    borderTopWidth: 1,
    gap: 3,
    marginTop: 12,
    paddingTop: 12,
  },
  recordTitle: {
    color: '#101b2d',
    fontSize: 16,
    fontWeight: '900',
  },
  recordTitleWrap: {
    flex: 1,
    paddingRight: 12,
  },
  recordTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 9,
  },
  records: {
    gap: 12,
  },
  screen: {
    backgroundColor: '#f3f7fb',
    flex: 1,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#eef8ff',
    borderColor: '#bce7ff',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
  },
  secondaryButtonText: {
    color: '#087cc2',
    fontSize: 15,
    fontWeight: '900',
  },
  sectionTitle: {
    color: '#101b2d',
    fontSize: 19,
    fontWeight: '900',
  },
  settingDescription: {
    color: '#718093',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  settingLabel: {
    color: '#101b2d',
    fontSize: 14,
    fontWeight: '900',
  },
  settingRow: {
    alignItems: 'center',
    backgroundColor: '#f6f9fd',
    borderColor: '#e7eef7',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  settingText: {
    flex: 1,
  },
  smallPrint: {
    color: '#79879a',
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  tab: {
    alignItems: 'center',
    borderRadius: 18,
    flex: 1,
    gap: 2,
    justifyContent: 'center',
    minHeight: 58,
  },
  tabActive: {
    backgroundColor: '#0ea5ff',
  },
  tabIcon: {
    color: '#91a0b4',
    fontSize: 14,
    fontWeight: '900',
  },
  tabText: {
    color: '#91a0b4',
    fontSize: 11,
    fontWeight: '900',
    marginTop: 4,
  },
  tabTextActive: {
    color: '#ffffff',
  },
  tabs: {
    backgroundColor: 'rgba(10, 26, 46, 0.92)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    padding: 8,
    position: 'absolute',
    left: 14,
    right: 14,
    ...shadow,
  },
  thresholdInput: {
    color: '#101b2d',
    fontWeight: '900',
    minWidth: 62,
    paddingHorizontal: 8,
    paddingVertical: 7,
    textAlign: 'right',
  },
  thresholdInputWrap: {
    alignItems: 'center',
    backgroundColor: '#f6f9fd',
    borderColor: '#e2e9f3',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
  },
  thresholdLabel: {
    color: '#263244',
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  thresholdRow: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    gap: 12,
  },
  thresholdSuffix: {
    color: '#718093',
    fontSize: 12,
    fontWeight: '900',
    paddingRight: 9,
  },
  title: {
    color: '#ffffff',
    fontSize: 25,
    fontWeight: '900',
  },
  userLine: {
    color: '#a7bad0',
    fontSize: 12,
    marginTop: 4,
  },
});
